In [12]:
# read test.xyz using pymatgen ase
# https://wiki.fysik.dtu.dk/ase/ase/neb.html
from pymatgen.io.ase import AseAtomsAdaptor
from ase.io import read

# read the structure
atoms = read('test.xyz')




In [2]:
atoms

Atoms(symbols='Mo64S126Se', pbc=True, cell=[[25.5225256, 0.0, 1.5628039641098191e-15], [-12.761262799999994, 22.10315553833868, 1.5628039641098191e-15], [0.0, 0.0, 14.879004]])

In [3]:
# visualize the structure
from ase.visualize import view
view(atoms)


<Popen: returncode: None args: ['/Users/andrey/micromamba/envs/m3gnet/bin/py...>

In [4]:
from m3gnet.models import M3GNet, M3GNetCalculator, Potential

In [5]:
model = M3GNet.load()

In [6]:
calculator = M3GNetCalculator(potential=Potential(model))

In [14]:
atoms.calc = calculator

In [9]:
atoms.get_potential_energy()

-1381.7024

In [11]:
# relax the structure using ASE
from ase.optimize import BFGS
from ase.constraints import UnitCellFilter
from ase.io import write

# relax the structure
relax = BFGS(UnitCellFilter(atoms))
relax.run(fmax=0.01)


      Step     Time          Energy         fmax
BFGS:    0 16:29:47    -1381.702393        2.0345
BFGS:    1 16:29:49    -1381.804443        1.3697
BFGS:    2 16:29:49    -1381.911987        0.8062
BFGS:    3 16:29:50    -1381.921021        0.3937
BFGS:    4 16:29:50    -1381.935059        0.1575
BFGS:    5 16:29:50    -1381.939941        0.1921
BFGS:    6 16:29:51    -1381.947632        0.1958
BFGS:    7 16:29:51    -1381.950439        0.1108
BFGS:    8 16:29:51    -1381.952637        0.0875
BFGS:    9 16:29:51    -1381.954590        0.0914
BFGS:   10 16:29:52    -1381.956177        0.1362
BFGS:   11 16:29:52    -1381.957520        0.1104
BFGS:   12 16:29:52    -1381.958252        0.0457
BFGS:   13 16:29:53    -1381.958984        0.0718
BFGS:   14 16:29:53    -1381.960083        0.0955
BFGS:   15 16:29:53    -1381.960815        0.0951
BFGS:   16 16:29:54    -1381.961304        0.0507
BFGS:   17 16:29:54    -1381.961670        0.0623
BFGS:   18 16:29:54    -1381.962036        0.0561
B

True

In [15]:
dyn = BFGS(atoms)
dyn.run(fmax=0.05)

      Step     Time          Energy         fmax
BFGS:    0 16:30:48    -1381.702393        2.0345
BFGS:    1 16:30:49    -1381.804077        1.3646
BFGS:    2 16:30:49    -1381.911865        0.3664
BFGS:    3 16:30:49    -1381.925415        0.2045
BFGS:    4 16:30:49    -1381.933350        0.2030
BFGS:    5 16:30:50    -1381.941406        0.1405
BFGS:    6 16:30:50    -1381.947144        0.0844
BFGS:    7 16:30:50    -1381.950317        0.0962
BFGS:    8 16:30:50    -1381.952393        0.0987
BFGS:    9 16:30:51    -1381.954590        0.0800
BFGS:   10 16:30:51    -1381.956299        0.0500


True

In [16]:
len(atoms)


191

In [17]:
dir(atoms)

['__add__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_ase_handles_dynamic_stress',
 '_calc',
 '_celldisp',
 '_cellobj',
 '_centering_as_array',
 '_constraints',
 '_del_constraints',
 '_get_atomic_numbers',
 '_get_constraints',
 '_get_positions',
 '_masked_rotate',
 '_pbc',
 '_set_positions',
 'append',
 'arrays',
 'ase_objtype',
 'calc',
 'cell',
 'center',
 'constraints',
 'copy',
 'edit',
 'euler_rotate',
 'extend',
 'fromdict',
 'get_all_distances',
 'get_angle',
 'get_angles',
 'get_angular_momentum',
 'get_array',
 'get_atomic_numbers',
 'get_calculator',
 'get_c

In [24]:
atoms.get_chemical_symbols()[126:]

['S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S',
 'S']

In [21]:
# count the number of atoms of each species
from collections import Counter 
Counter(atoms.get_chemical_symbols())


Counter({'S': 126, 'Mo': 64, 'Se': 1})

In [70]:
atoms.get_positions()[0]

array([0.00830158, 1.84287278, 3.72522661])

In [26]:
pos = atoms.get_positions()[-126:]

In [28]:
# count how many items in pos have coordinate z < 3
sum(pos[:,2] < 3)


63

In [29]:
sum(pos[:,2] > 3)


63

In [32]:
atoms.get_positions()[-127:-125]

array([[ 3.19030757, 14.73543237,  1.99074097],
       [ 1.6026201 ,  0.93056179,  2.15084662]])

In [34]:
atoms.get_chemical_symbols()[-127:-125]

['Se', 'S']

In [35]:
lower_pos = pos[pos[:,2] > 3]
lower_pos = pos[pos[:,2] < 3]

In [42]:
lower_pos[0], lower_pos[1]

(array([1.64017447, 0.92615948, 5.28043303]),
 array([1.61391713e-03, 3.68279233e+00, 5.28363335e+00]))

In [38]:
# find items that are present un upper_pos but that do not have a matching x, y coordinates in the lower_pos
# i.e. find atoms that have moved from the lower to the upper layer
# do comparison with precision of 0.1
# this is a bit of a hack, but it works
import numpy as np
np.isclose(lower_pos[:,0], lower_pos[:,0], atol=0.1)


for i in range(len(lower_pos)):
    el = lower_pos[i,:]
    for j in range(len(lower_pos)):
        lo = lower_pos[j,:]
        if np.isclose(el[0], lo[0], atol=0.1) and np.isclose(el[1], lo[1], atol=0.1):
            break
    else:
        print(i, el)


28 [ 3.19031001 14.73543384  5.26584681]


In [45]:
# find atoms in upper_pose near [ 3.19031001 14.73543384  5.26584681]
atol = 4
for i in range(len(lower_pos)):
    el = lower_pos[i,:]
    distance = np.linalg.norm(el - [ 3.19031001, 14.73543384,  5.26584681])
    if distance < atol:
        print(i, el, distance)

19 [ 1.59134315 11.96845165  5.28951969] 3.195848221193334
20 [-5.45007980e-03  1.47341790e+01  5.28951978e+00] 3.1958480150796027
27 [ 4.78934336 11.96844552  5.28950464] 3.195886684618014
28 [ 3.19031001 14.73543384  5.26584681] 2.9255899877447187e-09
29 [ 1.59354458 17.50373095  5.28950473] 3.1958861707875306
36 [ 6.38592305 14.7340166   5.28961403] 3.195701738944464
37 [ 4.78688913 17.50362396  5.28961408] 3.195701223073735


In [47]:
atol = 4
for i in range(len(lower_pos)):
    el = lower_pos[i,:]
    distance = np.linalg.norm(el - [ 3.19031001, 14.73543384,  2.16584681])
    if distance < atol:
        print(i, el, distance)

20 [ 1.59172737 11.96274512  2.16905921] 3.2005123826267936
21 [-1.01999881e-02  1.47373648e+01  2.16905908e+00] 3.200512192626156
28 [ 4.7889542  11.96273873  2.16907529] 3.200548679095291
29 [ 1.58840784 17.5062475   2.16907524] 3.200548284484255
36 [ 6.39067739 14.73721036  2.1689762 ] 3.2003694052726606
37 [ 4.79203229 17.50614508  2.16897618] 3.200369488081134


In [71]:
atoms_final = atoms.copy()

In [55]:
# move atom with coordinates [ 6.39067739 14.73721036  2.1689762 ] to [ 3.19031001, 14.73543384,  2.16584681] coordinates

# find the index of the atom with coordinates [ 6.39067739 14.73721036  2.1689762 ]
pos = atoms_final.get_positions()
for i in range(len(pos)):
    el = pos[i,:]
    distance = np.linalg.norm(el - [ 6.39067739, 14.73721036,  2.1689762 ])
    if distance < 0.1:
        print(i, el, distance)


In [72]:
# set position of atom 101 to equal [ 3.19031001, 14.73543384,  2.16584681]
atoms_final.positions[144] = [ 4.785, 0.921,  5.2658]

In [73]:
view(atoms_final)

<Popen: returncode: None args: ['/Users/andrey/micromamba/envs/m3gnet/bin/py...>

In [74]:
images = [atoms]
images += [atoms.copy() for i in range(3)]
images += [atoms_final]

In [75]:
from ase.neb import NEB
from ase.optimize import MDMin

In [76]:
neb = NEB(images)

In [77]:
neb.interpolate()

In [78]:
for image in images[1:4]:
    image.calc = M3GNetCalculator(potential=Potential(model))

In [79]:
optimizer = MDMin(neb, trajectory='A2B.traj')

In [80]:
optimizer.run(fmax=0.04)


       Step     Time          Energy         fmax
MDMin:    0 18:25:10    -1377.543335       25.7944
MDMin:    1 18:25:16    -1378.639893       12.9071
MDMin:    2 18:25:16    -1380.608032        1.7496
MDMin:    3 18:25:17    -1380.988525        1.1669
MDMin:    4 18:25:17    -1381.172852        1.0930
MDMin:    5 18:25:17    -1381.215210        0.5032
MDMin:    6 18:25:18    -1381.252197        0.3173
MDMin:    7 18:25:18    -1381.276123        0.2187
MDMin:    8 18:25:18    -1381.289307        0.2272
MDMin:    9 18:25:19    -1381.297852        0.1399
MDMin:   10 18:25:19    -1381.302490        0.1096
MDMin:   11 18:25:19    -1381.307251        0.0791
MDMin:   12 18:25:20    -1381.311157        0.0953
MDMin:   13 18:25:20    -1381.313477        0.1435
MDMin:   14 18:25:21    -1381.315674        0.0460
MDMin:   15 18:25:21    -1381.317139        0.0399


True

In [81]:
# visualize the trajectory
from ase.visualize import view
view(images)

<Popen: returncode: None args: ['/Users/andrey/micromamba/envs/m3gnet/bin/py...>

In [68]:
view(atoms)

<Popen: returncode: None args: ['/Users/andrey/micromamba/envs/m3gnet/bin/py...>

In [69]:
view(atoms_final)

<Popen: returncode: None args: ['/Users/andrey/micromamba/envs/m3gnet/bin/py...>

In [83]:
images[1].get_potential_energy(), images[2].get_potential_energy(), images[3].get_potential_energy(), 

(-1381.4408, -1381.3171, -1381.4683)